### ISSUE TITLE
Trade command failing in NBA leagues

### ISSUE THREAD

**Issue by DMcP89** [DMcP89/harambot#76]
**Describe the bug**
trade command is not working as expected for NBA leagues

**To Reproduce**
Run the trade command while a trade is up for approval

**Expected behavior**
Harambot should post the trade details to the channel for voting

```
2022-10-16T21:01:54.444173+00:00 app[worker.1]: [2022-10-16 21:01:54,444 INFO] [/app/harambot/cogs/yahoo.py.yahoo.trade] trade called
2022-10-16T21:01:55.257737+00:00 app[worker.1]: Error while fetching player details for player: Aaron Gordon in league 15944
2022-10-16T21:01:55.257771+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-16T21:01:55.257771+00:00 app[worker.1]:   File "/app/harambot/yahoo_api.py", line 82, in get_player_details
2022-10-16T21:01:55.257772+00:00 app[worker.1]:     embed.add_field(name="Total Points", value=player['player_points']['total'])
2022-10-16T21:01:55.257773+00:00 app[worker.1]: KeyError: 'player_points'
2022-10-16T21:01:55.260232+00:00 app[worker.1]: [2022-10-16 21:01:55,259 ERROR] [discord.ext.commands.bot.bot.on_command_error] Ignoring exception in command trade
2022-10-16T21:01:55.260232+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-16T21:01:55.260233+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 190, in wrapped
2022-10-16T21:01:55.260233+00:00 app[worker.1]:     ret = await coro(*args, **kwargs)
2022-10-16T21:01:55.260234+00:00 app[worker.1]:   File "/app/harambot/cogs/yahoo.py", line 72, in trade
2022-10-16T21:01:55.260235+00:00 app[worker.1]:     api_details = self.yahoo_api.get_player_details(player['name'])["text"]+"\n"
2022-10-16T21:01:55.260235+00:00 app[worker.1]: TypeError: 'NoneType' object is not subscriptable
2022-10-16T21:01:55.260236+00:00 app[worker.1]: 
2022-10-16T21:01:55.260236+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2022-10-16T21:01:55.260237+00:00 app[worker.1]: 
2022-10-16T21:01:55.260237+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-16T21:01:55.260237+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
2022-10-16T21:01:55.260237+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2022-10-16T21:01:55.260237+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 986, in invoke
2022-10-16T21:01:55.260237+00:00 app[worker.1]:     await injected(*ctx.args, **ctx.kwargs)  # type: ignore
2022-10-16T21:01:55.260238+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 199, in wrapped
2022-10-16T21:01:55.260238+00:00 app[worker.1]:     raise CommandInvokeError(exc) from exc
2022-10-16T21:01:55.260238+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable
2022-10-16T21:01:55.260267+00:00 app[worker.1]: [2022-10-16 21:01:55] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command trade
2022-10-16T21:01:55.260267+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-16T21:01:55.260267+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 190, in wrapped
2022-10-16T21:01:55.260267+00:00 app[worker.1]:     ret = await coro(*args, **kwargs)
2022-10-16T21:01:55.260267+00:00 app[worker.1]:   File "/app/harambot/cogs/yahoo.py", line 72, in trade
2022-10-16T21:01:55.260268+00:00 app[worker.1]:     api_details = self.yahoo_api.get_player_details(player['name'])["text"]+"\n"
2022-10-16T21:01:55.260268+00:00 app[worker.1]: TypeError: 'NoneType' object is not subscriptable
2022-10-16T21:01:55.260268+00:00 app[worker.1]: 
2022-10-16T21:01:55.260268+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2022-10-16T21:01:55.260268+00:00 app[worker.1]: 
2022-10-16T21:01:55.260268+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-16T21:01:55.260268+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
2022-10-16T21:01:55.260269+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2022-10-16T21:01:55.260269+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 986, in invoke
2022-10-16T21:01:55.260269+00:00 app[worker.1]:     await injected(*ctx.args, **ctx.kwargs)  # type: ignore
2022-10-16T21:01:55.260279+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 199, in wrapped
2022-10-16T21:01:55.260279+00:00 app[worker.1]:     raise CommandInvokeError(exc) from exc
2022-10-16T21:01:55.260279+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable
```

**Comment by DMcP89** [comment]
This shares the same root cause as #73, closing as duplicate
